//councils list
export const COUNCIL_LIST_REQUEST = "COUNCIL_LIST_REQUEST";
export const COUNCIL_LIST_SUCCESS = "COUNCIL_LIST_SUCCESS";
export const COUNCIL_LIST_FAIL = "COUNCIL_LIST_FAIL";
//council add
export const COUNCIL_ADD_REQUEST = "COUNCIL_ADD_REQUEST";
export const COUNCIL_ADD_SUCCESS = "COUNCIL_ADD_SUCCESS";
export const COUNCIL_ADD_FAIL = "COUNCIL_ADD_FAIL";
export const COUNCIL_ADD_RESET = "COUNCIL_ADD_RESET";
